export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <>
        
        {children}
        <h3>This is a carosle for featured products</h3>
      </>
    )
  }
  